services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: NPM
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./volumes/data:/data
      - ./volumes/letsencrypt:/etc/letsencrypt
    networks:
        - proxy


networks:
  proxy:
    driver: bridge


