- id: '1753700249742'
  alias: Leaving Work
  description: ''
  triggers:
  - device_id: d63398366a8d1b9dd522022508ea86c0
    domain: device_tracker
    entity_id: 0699e303e55ba01731f28833c2e614ac
    type: leaves
    trigger: device
    zone: zone.frankie_s_work
  conditions:
  - condition: time
    after: '16:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - device_id: a01d0ee4428dd29d1eaf512d4e7fe2c3
    domain: mobile_app
    type: notify
    message: Frankie's leaving work!
  mode: single
- id: '1754068982797'
  alias: Ellie's Btn Pressed
  description: ''
  triggers:
  - device_id: f77630cb24ee7913a410d278c2ca0700
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    data: {}
    target:
      area_id: ellie_s_room
  mode: single
- id: '1755004808813'
  alias: Bedroom Btn Double Pressed
  description: ''
  triggers:
  - device_id: eb49e8d861260e48b9f9f0c65c44e304
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      transition: 2
      brightness_pct: 100
      color_temp_kelvin: 4813
    target:
      device_id: 99101c0bcd66d8e4d3532b7c03afbc44
  mode: single
- id: '1755212102324'
  alias: 'Kitchen Motion Lights '
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.kitchen_presence_sensor
      light_target:
        area_id: kitchen
      no_motion_wait: 0
- id: '1755946736163'
  alias: Bedroom Btn Pressed w/ ligths off
  description: ''
  triggers:
  - device_id: eb49e8d861260e48b9f9f0c65c44e304
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions:
  - condition: and
    conditions:
    - condition: device
      type: is_off
      device_id: 99101c0bcd66d8e4d3532b7c03afbc44
      entity_id: 67db6b7fabd03a2a7e31a3ee06403967
      domain: light
    - condition: device
      type: is_off
      device_id: 8cc3f355ed7e71b1039c01b8091ecbb3
      entity_id: 0c4fe33636478cc1962a0741f4bf4f36
      domain: switch
  actions:
  - if:
    - condition: sun
      before: sunrise
      after: sunset
    then:
    - action: scene.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: scene.new_scene
    else:
    - action: light.turn_on
      metadata: {}
      data: {}
      target:
        device_id: 99101c0bcd66d8e4d3532b7c03afbc44
  mode: single
- id: '1755947076728'
  alias: Bedroom Btn Pressed \w lights on
  description: ''
  triggers:
  - device_id: eb49e8d861260e48b9f9f0c65c44e304
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions:
  - condition: or
    conditions:
    - condition: device
      type: is_on
      device_id: 99101c0bcd66d8e4d3532b7c03afbc44
      entity_id: 67db6b7fabd03a2a7e31a3ee06403967
      domain: light
    - condition: device
      type: is_on
      device_id: 8cc3f355ed7e71b1039c01b8091ecbb3
      entity_id: 0c4fe33636478cc1962a0741f4bf4f36
      domain: switch
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id: bedroom
  - type: turn_off
    device_id: 8cc3f355ed7e71b1039c01b8091ecbb3
    entity_id: 0c4fe33636478cc1962a0741f4bf4f36
    domain: switch
  mode: single
- id: '1755947185380'
  alias: Bedroom Btn Long Pressed
  description: ''
  triggers:
  - device_id: eb49e8d861260e48b9f9f0c65c44e304
    domain: zha
    type: remote_button_long_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id: bedroom
  - type: turn_on
    device_id: 8cc3f355ed7e71b1039c01b8091ecbb3
    entity_id: 0c4fe33636478cc1962a0741f4bf4f36
    domain: switch
  mode: single
- id: '1755982039691'
  alias: Ellie's Btn Double Pressed
  description: ''
  triggers:
  - device_id: f77630cb24ee7913a410d278c2ca0700
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
      color_temp_kelvin: 4732
    target:
      device_id: 9ac24b0298e6df6ceda384d3384f4590
  mode: single
- id: '1756018297462'
  alias: 'Leaving home '
  description: ''
  triggers:
  - trigger: zone
    entity_id: person.francisco_power
    zone: zone.home
    event: leave
  - trigger: zone
    entity_id: person.angelica
    zone: zone.home
    event: leave
  conditions:
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.angelica
      zone: zone.home
    - condition: zone
      entity_id: person.francisco_power
      zone: zone.home
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id:
      - bedroom
      - ellie_s_room
      - kitchen
      - living_room
  - type: turn_off
    device_id: 8cc3f355ed7e71b1039c01b8091ecbb3
    entity_id: 0c4fe33636478cc1962a0741f4bf4f36
    domain: switch
  - action: script.notify_to_vacuum_the_house
    data: {}
  mode: single
- id: '1756158673667'
  alias: Kitchen Night Motion Lights
  description: Turns on kitchen lights when motion is detected between 11 PM and 6
    AM, and turns them off when motion stops and the kitchen is no longer occupied.
  triggers:
  - type: occupied
    device_id: 6c2e8bafd11f93eaaa92607d68833677
    entity_id: b09c923070623faacab4d9404b5447cd
    domain: binary_sensor
    trigger: device
    id: motion_start
  - type: not_occupied
    device_id: 6c2e8bafd11f93eaaa92607d68833677
    entity_id: b09c923070623faacab4d9404b5447cd
    domain: binary_sensor
    trigger: device
    id: motion_end
  conditions:
  - condition: time
    after: '23:00:00'
    before: 06:00:00
  actions:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - motion_start
      sequence:
      - action: light.turn_on
        metadata: {}
        data:
          brightness_pct: 100
        target:
          device_id: d146f6075d24738d742ae8ec63d3ed4d
    - conditions:
      - condition: trigger
        id:
        - motion_end
      - type: is_not_occupied
        condition: device
        device_id: 2c6d492ae22cc644c4306a59d5045562
        entity_id: 486f2d33fa69ebe46deaed1de1f0a0f1
        domain: binary_sensor
      sequence:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          device_id: d146f6075d24738d742ae8ec63d3ed4d
  mode: single
