- id: '1753398280332'
  alias: 'Leaving home '
  description: ''
  triggers:
  - trigger: zone
    entity_id: person.angelica
    zone: zone.home
    event: leave
  conditions:
  - condition: zone
    entity_id: person.francisco_power
    zone: zone.home
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id:
      - 99101c0bcd66d8e4d3532b7c03afbc44
      - 9ac24b0298e6df6ceda384d3384f4590
      - d146f6075d24738d742ae8ec63d3ed4d
      - 36ba8d8d619f76af150f27bb1f18c4f7
  mode: single
- id: '1753399106551'
  alias: 'Lights out at night '
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.wvnq93vm7r_battery_state
    from: Not Charging
    to: Charging
  conditions:
  - condition: zone
    entity_id: person.francisco_power
    zone: zone.home
  - condition: time
    after: '23:00:00'
    before: 05:00:00
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id:
      - d146f6075d24738d742ae8ec63d3ed4d
      - 36ba8d8d619f76af150f27bb1f18c4f7
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      device_id: 8cc3f355ed7e71b1039c01b8091ecbb3
  - if:
    - condition: or
      conditions:
      - condition: device
        type: is_on
        device_id: 99101c0bcd66d8e4d3532b7c03afbc44
        entity_id: 67db6b7fabd03a2a7e31a3ee06403967
        domain: light
      - condition: device
        type: is_on
        device_id: 8cc3f355ed7e71b1039c01b8091ecbb3
        entity_id: 0c4fe33636478cc1962a0741f4bf4f36
        domain: switch
    then:
    - action: light.turn_on
      metadata: {}
      data:
        color_temp_kelvin: 2000
        brightness_pct: 10
      target:
        device_id: 99101c0bcd66d8e4d3532b7c03afbc44
  mode: single
- id: '1753700249742'
  alias: Leaving Work
  description: ''
  triggers:
  - device_id: d63398366a8d1b9dd522022508ea86c0
    domain: device_tracker
    entity_id: 0699e303e55ba01731f28833c2e614ac
    type: leaves
    trigger: device
    zone: zone.frankie_s_work
  conditions:
  - condition: time
    after: '16:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  actions:
  - device_id: a01d0ee4428dd29d1eaf512d4e7fe2c3
    domain: mobile_app
    type: notify
    message: Frankie's leaving work!
  mode: single
- id: '1753889948954'
  alias: Bedtime button
  description: ''
  triggers:
  - device_id: eb49e8d861260e48b9f9f0c65c44e304
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions:
  - condition: and
    conditions:
    - condition: device
      type: is_off
      device_id: 99101c0bcd66d8e4d3532b7c03afbc44
      entity_id: 67db6b7fabd03a2a7e31a3ee06403967
      domain: light
    - condition: device
      type: is_off
      device_id: 8cc3f355ed7e71b1039c01b8091ecbb3
      entity_id: 0c4fe33636478cc1962a0741f4bf4f36
      domain: switch
  actions:
  - action: scene.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: scene.new_scene
  mode: single
- id: '1753890727945'
  alias: Kitchen Lights On
  description: ''
  triggers:
  - type: turned_on
    device_id: 530032e09dab84b6ec0ee6b2a6567a2d
    entity_id: f5823b59c994363d1cb4df1e660dee2e
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      area_id: kitchen
  mode: single
- id: '1753890797701'
  alias: Kitchen Lights off
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.unk_manufacturer_unk_model
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id: kitchen
  mode: single
- id: '1753906301577'
  alias: Button Lights off
  description: ''
  triggers:
  - device_id: eb49e8d861260e48b9f9f0c65c44e304
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions:
  - condition: or
    conditions:
    - condition: device
      type: is_on
      device_id: 99101c0bcd66d8e4d3532b7c03afbc44
      entity_id: 67db6b7fabd03a2a7e31a3ee06403967
      domain: light
    - condition: device
      type: is_on
      device_id: 8cc3f355ed7e71b1039c01b8091ecbb3
      entity_id: 0c4fe33636478cc1962a0741f4bf4f36
      domain: switch
  actions:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      area_id: bedroom
  - type: turn_off
    device_id: 8cc3f355ed7e71b1039c01b8091ecbb3
    entity_id: 0c4fe33636478cc1962a0741f4bf4f36
    domain: switch
  mode: single
