services:
  yacht:
    container_name: yacht
    restart: unless-stopped
    volumes:
      - ./volumes/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    image: selfhostedpro/yacht
    networks:
      - proxy

networks:
  proxy:
    name: nginx-proxy_proxy
    external: true

