services:
  upsnap:
    container_name: upsnap
    image: ghcr.io/seriousm4x/upsnap:4 # images are also available on docker hub: seriousm4x/upsnap:4
    network_mode: host
    restart: unless-stopped
    volumes:
      - ~/docker/UpSnap/data:/app/pb_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.upsnap.rule=Host(`wol.npowers.net`)"
      - "traefik.http.services.upsnap.loadbalancer.server.port=8090"

